### ISSUE TITLE
Catkin_make error include directory not found

### ISSUE THREAD

**Issue by Gaurav37** [introlab/audio_utils#13]
I followed all steps including git submodule update --init --recursive
When I catkin_make I get:

CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:305 (message):
  catkin_package() include dir
  'src/MusicBeatDetector/3rdParty/fftw/build/include' does not exist relative
  to '/home/hello-robot/gaurav_ws/src/audio_utils'
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  audio_utils/CMakeLists.txt:112 (catkin_package)

-- Configuring incomplete, errors occurred!
See also "/home/hello-robot/gaurav_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/hello-robot/gaurav_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:1067: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by mamaheux** [comment]
Hi,
I have fixed the issue in the latest commit.
