### ISSUE TITLE
I have followed all steps but somehow its giving gfortran error during catkin_make

### ISSUE THREAD

**Issue by Gaurav37** [introlab/audio_utils#8]
This is my error:

[ 87%] Linking CXX executable /home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/beat_detector_node
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
audio_utils/CMakeFiles/alsa_playback_node.dir/build.make:194: recipe for target '/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/alsa_playback_node' failed
make[2]: *** [/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/alsa_playback_node] Error 1
CMakeFiles/Makefile2:2262: recipe for target 'audio_utils/CMakeFiles/alsa_playback_node.dir/all' failed
make[1]: *** [audio_utils/CMakeFiles/alsa_playback_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
audio_utils/CMakeFiles/alsa_capture_node.dir/build.make:168: recipe for target '/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/alsa_capture_node' failed
make[2]: *** [/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/alsa_capture_node] Error 1
CMakeFiles/Makefile2:1936: recipe for target 'audio_utils/CMakeFiles/alsa_capture_node.dir/all' failed
make[1]: *** [audio_utils/CMakeFiles/alsa_capture_node.dir/all] Error 2
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
audio_utils/CMakeFiles/beat_detector_node.dir/build.make:116: recipe for target '/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/beat_detector_node' failed
make[2]: *** [/home/gaurav/catkin_ws_stretch/devel/lib/audio_utils/beat_detector_node] Error 1
CMakeFiles/Makefile2:2126: recipe for target 'audio_utils/CMakeFiles/beat_detector_node.dir/all' failed
make[1]: *** [audio_utils/CMakeFiles/beat_detector_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by mamaheux** [comment]
Hi, can you execute the following command and send me the result?
```bash
apt list --installed | grep gfortran
```

Thanks

**Comment by Gaurav37** [comment]
This error was when I was trying to install on my laptop without any physical usb ring present. In robot it worked.
